name: CI

on:
  workflow_dispatch:
    inputs:
    environment:
      description: "Manual deployment"
      required: true
      default: "staging"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
